# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Github
    url: https://github.com/minibugdev
    weight: 20
  - name: Contact
    url: mailto:teeranai.buddee@gmail.com
    weigth: 30
